import Link from "next/link";
import "./globals.css";
import "./pulse_bootstrap.min.css";
import { Inter } from "next/font/google";
import page from "./header/page";
import HeaderPage from "./header/page";
import { Provider } from "react-redux";
import App from "./Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CURD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderPage />
        <App>{children}</App>
      </body>
    </html>
  );
}
